### ISSUE TITLE
Remove fixed Go version in Github Actions when go modules issue is resolved

### ISSUE THREAD

**Issue by mike1808** [vmware-tanzu/cross-cluster-connectivity#103]
Currently, with the latest version of Go used in the test in Github actions we cannot build our packages. 
We pinned our Go version to the one which doesn't have this issue. 

However, when https://github.com/golang/go/issues/44129 is resolved we have to revert our changes and set golang version to the latest.

Here are the lines which were changed to make our test pass in CI:
https://github.com/vmware-tanzu/cross-cluster-connectivity/blob/0526feb23b4459ae25ef7b02807bf0407ea8606e/.github/workflows/test.yaml#L11
https://github.com/vmware-tanzu/cross-cluster-connectivity/blob/0526feb23b4459ae25ef7b02807bf0407ea8606e/.github/workflows/test.yaml#L22
https://github.com/vmware-tanzu/cross-cluster-connectivity/blob/0526feb23b4459ae25ef7b02807bf0407ea8606e/.github/workflows/test.yaml#L37
https://github.com/vmware-tanzu/cross-cluster-connectivity/blob/0526feb23b4459ae25ef7b02807bf0407ea8606e/.github/workflows/test.yaml#L40

**Comment by adobley** [comment]
According to the [most recent updates](https://github.com/golang/go/issues/44129#issuecomment-865249631), 
> This should be fixed in Go 1.17. We don't plan to backport the fix to 1.16.x; in order to avoid unintended regressions, we normally only backport fixes for security vulnerabilities and severe issues with no workaround.

Go 1.17 is expected in August, so we can check this again after that.

**Comment by adobley** [comment]
We should be able to act on this now that Go 1.17 has been released: https://blog.golang.org/go1.17
