### ISSUE TITLE
Error installing the xcc-dns-controller: {"error": "no matches for kind \"Cluster\" in version \"cluster.x-k8s.io/v1alpha3\""}

### ISSUE THREAD

**Issue by dirk-olmes** [vmware-tanzu/cross-cluster-connectivity#109]
## Short Description
Error installing the `xcc-dns-controller`: 
```
{"error": "no matches for kind \"Cluster\" in version \"cluster.x-k8s.io/v1alpha3\""}
```

## Steps To Reproduce
I'm following the Walkthrough steps in the README. In step 2 I install the `xcc-dns-controller` deployment but the pod goes into a crash loop - see attached logfile.

## Expected Behavior
`xcc-dns-controller` should be up and running

## Environment:
 - Cross-cluster connectivity version: master branch commit bc2e8e4c521e6d9dd92ab2de58552907a64bd9a5
 - Kubernetes version: (use `kubectl version`): k8s v1.20.7+vmware.1-tkg.1.7fb9067, kubectl v1.19.1+wcp.3
 - Cloud provider or hardware configuration: Tanzu Kubernetes

## Logfiles
[xcc-dns-controller-6b44dddc48-bkqgd.log](https://github.com/vmware-tanzu/cross-cluster-connectivity/files/7160756/xcc-dns-controller-6b44dddc48-bkqgd.log)

**Comment by christianang** [comment]
Sorry for the delayed response on this. We bump the dependencies for this repo so this error should go away once #111 is merged.
