### ISSUE TITLE
Speed up e2e  tests

### ISSUE THREAD

**Issue by mcwumbly** [vmware-tanzu/cross-cluster-connectivity#20]
## Description

The [initial step in the journey test](https://github.com/vmware-tanzu/cross-cluster-connectivity/blob/a8d3a91180a44d5c051aad5cf06a406099db8d66/test/connectivity/exported_service_test.go#L86-L91) uses a `Consistently` with a 1 minute timeout to verify the initial state:

```
		By("validating it doesn't discover the shared service on the workload cluster")
		Consistently(func() (string, error) {
			output, err := kubectlWithConfig(workloadClusterKubeConfig,
				"get", "svc", "-n", connectivityv1alpha1.ConnectivityNamespace)
			return string(output), err
		}, kubectlTimeout, kubectlInterval).ShouldNot(ContainSubstring("nginx-xcc-test"))
```

I'm not sure why this is necessary to check at all, let alone for a full minute.

## Desired Solution

I think this block can be removed completely. Though I may be missing some historical context about why this might be a good guard to have in place.

## Alternatives Considered

If this block has proven helpful in the past, perhaps the timeout can be reduced significantly, or it can be checked once instead of in a `Consistently`

## Additional Context

I think we should aim to keep our tests as fast as possible.

**Comment by christianang** [comment]
On a call we agreed that the consistently doesn't make sense, it can either change to an expect or an eventually.
