### ISSUE TITLE
Consider using `ytt` instead of `sed` in scripts

### ISSUE THREAD

**Issue by flawedmatrix** [vmware-tanzu/cross-cluster-connectivity#22]
## Description
Similar to the change made in #18, this part of the e2e.sh script would be more readable using `ytt` instead of using `sed`:
https://github.com/vmware-tanzu/cross-cluster-connectivity/blob/307b3dadcaceca325782d119cb6e67a1318220b8/hack/e2e.sh#L214-L218

There may be other places where `sed` is used that could also benefit.

## Desired Solution
- A reduction in the use of `sed` in scripts

**Comment by christianang** [comment]
Looking at what might change with using ytt. I'm not convinced this would make that bit of code any more readable or simpler. If we see using ytt as a way to make this part easier to work with, then it feels like a premature optimization. I would advocate for changing this only when we have a need.

**Comment by flawedmatrix** [comment]
Makes sense. I'll close this issue for now.
