### ISSUE TITLE
connectivity-publisher should only delete Service Records it created

### ISSUE THREAD

**Issue by jamiemonserrate** [vmware-tanzu/cross-cluster-connectivity#29]
## Description
When the connectivity-publisher is looking to delete orphan Service Records, it should only delete Service Records that have been created by the connectivity-publisher, and not ones that have been manually created / created by other solutions. 

## Desired Solution
Add an annotation at create time to indicate that the ServiceRecord was created by the connectivity-publisher. 

## Alternatives Considered
OwnerReference - We can't use these since the service record could be created in a different namespace as the ExportedHTTPProxy. 

## Additional Context
Came up during a team discussion for https://github.com/vmware-tanzu/cross-cluster-connectivity/pull/27

**Comment by rosenhouse** [comment]
I've seen other controllers adopt patterns like ReplicaSet does: require a template that includes labels to apply to children, and have the controller only watch for those children.

If we're considering a different direction, I'd want to make sure we know why.

**Comment by rosenhouse** [comment]
On further thought, I'd rather we change the Publisher to be fully-namespaced, i.e. to create ServiceRecords in the same namespace as the HTTPProxy.  Then we can rely on `ownerRef` to ensure cleanup

**Comment by christianang** [comment]
This issue will be accomplished by this: https://github.com/vmware-tanzu/cross-cluster-connectivity/issues/33. We will close this issue when the other is done.
