### ISSUE TITLE
Publisher should create ServiceRecords in the same namespace as the HTTPProxy.  RegistryServer should watch multiple namespaces

### ISSUE THREAD

**Issue by rosenhouse** [vmware-tanzu/cross-cluster-connectivity#33]
making an issue out of [this comment](https://github.com/vmware-tanzu/cross-cluster-connectivity/issues/29#issuecomment-724335658)

Let's change the Publisher to be fully-namespace-aware, i.e. to watch for HTTPProxy resources in all namespaces, and to create the ServiceRecord in the same namespace as the HTTPProxy. Then we can rely on ownerReferences to ensure cleanup of the ServiceRecords.

Then the RegistryServer can be configured to watch for 1/some/all namespaces when serving.

**Comment by mcwumbly** [comment]
Another nice impact of this change (if I understand correctly, and perhaps obviously) is the feedback it provides to the user adding the `export` label to their `HTTProxy` resource, as they will now be able to see the `ServiceRecord` that gets created due to that declaration of intent when they list resources in their namespace.

**Comment by rosenhouse** [comment]
Capturing some notes from our call:
- Publisher binary could be running in a "system" namespace
- Think through downtime implications, e.g. existing systems relying on the ServiceRecord in a "system" namespace

**Comment by christianang** [comment]
Also worth checking to make sure our RBAC for the publisher is updated to allow writing ServiceRecords to any namespace.

**Comment by rosenhouse** [comment]
Our publisher will only reconcile against HTTPProxy (for now).  Therefore:
- if it encounters a ServiceRecord w/ ownerRef to an HTTPProxy, and if that HTTPProxy is unlabeled, then our controller should delete the ServiceRecord.
- if the ownerRef doesn't exist, or points at an object other than HTTPProxy, then no-op

**Comment by christianang** [comment]
We might also want to update our architecture doc in the same PR to keep it up-to-date: https://github.com/vmware-tanzu/cross-cluster-connectivity/blob/main/doc/arch.md. Namely the diagram.
