### ISSUE TITLE
Container images in manifests should be publicly pull-able

### ISSUE THREAD

**Issue by rosenhouse** [vmware-tanzu/cross-cluster-connectivity#62]
## Description
Applying the deployment files currently on `main` in `manifests/*/deployment.yaml` lead to failed pods because the referenced container images aren't pull-able.

E.g. 
```
kubectl apply -f manifests/dns-server/deployment.yaml
```
and then
```
k describe pods -n capi-dns -l app=dns-server
```
shows errors like 
```
Events:
  Type     Reason     Age                   From               Message
  ----     ------     ----                  ----               -------
  Normal   Scheduled  19m                   default-scheduler  Successfully assigned capi-dns/dns-server-9f5796b7b-58nms to cluster-a-md-0-77674c9657-7jcsb
  Normal   Pulling    17m (x4 over 19m)     kubelet            Pulling image "ghcr.io/vmware-tanzu/cross-cluster-connectivity/dns-server:dev"
  Warning  Failed     17m (x4 over 19m)     kubelet            Failed to pull image "ghcr.io/vmware-tanzu/cross-cluster-connectivity/dns-server:dev": rpc error: code = Unknown desc = failed to pull and unpack image "ghcr.io/vmware-tanzu/cross-cluster-connectivity/dns-server:dev": failed to resolve reference "ghcr.io/vmware-tanzu/cross-cluster-connectivity/dns-server:dev": failed to authorize: failed to fetch anonymous token: unexpected status: 403 Forbidden
  Warning  Failed     17m (x4 over 19m)     kubelet            Error: ErrImagePull
  Warning  Failed     17m (x6 over 19m)     kubelet            Error: ImagePullBackOff
  Normal   BackOff    4m14s (x64 over 19m)  kubelet            Back-off pulling image "ghcr.io/vmware-tanzu/cross-cluster-connectivity/dns-server:dev"
```

## Desired Solution
The manifests on `main` should be deployable as-is.

Maybe CI can ensure that the images at `ghcr.io/vmware-tanzu/cross-cluster-connectivity/` are public?  May need to think through the relationship between container tags and our git branch/tag flow.

## Alternatives Considered
- Docs that reference a tagged "release" that we manually put up?  Idk, that sounds worse?
- Tell people to push images to their own registry?

## Additional Context
We don't have install docs yet.  Maybe I'm missing something obvious?

**Comment by tylerschultz** [comment]
The fan in behavior does not work the way we desire. We want to run publish after both test and check license. The workflow behavior runs once after each of those steps. A followup commit will combine check license and test workflows, and the publish workflow will depend on the combined test and check license workflows.
