### ISSUE TITLE
Rename capi-dns-service-watcher and capi-dns-controller

### ISSUE THREAD

**Issue by adobley** [vmware-tanzu/cross-cluster-connectivity#82]
## Description
Issue #61 renames the `capi-dns` namespace to `xcc-dns`. 

We feel it would be ideal to stay consistent with our naming.

We wanted to open this up to others and get input.

## Desired Solution
`capi-dns-service-watcher` is renamed to `xcc-dns-service-watcher`
`capi-dns-controller` is renamed to `xcc-dns-controller`

## Alternatives Considered
Open to alternative suggestions for naming or arguments to keep the names. 
The controller is specifically for Cluster API, so we do see an argument for that name remaining unchanged.

**Comment by mcwumbly** [comment]
i'm in favor of the suggested name change. if we later had controllers that integrated with different interfaces we could disambiguate and do something like `xcc-capi-dns-controller`, etc.
